dataset_name: passive_biv
data_type: validation
sections: [0, 20, 100, 250, 500, 1000]
nodes_per_sections: [20, 30, 30, 10, 10]
down_sample_node: 10000
device: "cpu"
normalize_val_objective: True

model_path: log/passive_biv/non_norm_5_3/model/model_3000.pth
selected_node: 20
select_edge_num: 12

output_path: ./phy_gnn/task/passive_biv/tmp_for_test/test_model_5_3/